### ISSUE TITLE
Links not updated on training-center website 

### ISSUE THREAD

**Issue by martamaja10** [HSF/hsf.github.io#1588] opened 2024-09-18 08:02 UTC
My [PR](https://github.com/HSF/hsf.github.io/pull/1584) to update the ROOT links: https://hsf-training.org/training-center/ was merged two days ago, but the website hasn't updated and the old course is still linked. Also, if I try to go into About I get the file not found error: https://hepsoftwarefoundation.org/workinggroups/training.html . 

I also slightly modified the ROOT GSOC description and that part worked fine.

**Comment by graeme-a-stewart** [comment] 2024-09-20 09:45
Hi @jpivarski @amorenobr - could you take a look? Is this to do with the way the new training centre is coded? Like a different repo?

**Comment by jpivarski** [comment] 2024-09-20 13:56
@ariostas, do you see what the issue is? #1584 updated

* _data/training-modules.yaml
* _gsocprojects/2024/project_ROOT.md

What is the intended pathway for changes in these source files to update the final HTML?

**Comment by ariostas** [comment] 2024-09-20 15:22
@martamaja10, the training center was moved to https://github.com/hsf-training/training-center since now it's not Jekyll based.

I hadn't removed the training center data from this repo in case we had to roll back, but now it's just making things confusing. Sorry about that! I'll open a PR to remove things and point people to the new repo.

**Comment by ariostas** [comment] 2024-09-20 16:06
> Can the old URL be an automatic redirect to the new one?

Yeah, the old URL already redirects to the new one, but on GitHub it's not clear that it moved somewhere else

**Comment by martamaja10** [comment] 2024-09-23 07:18
Thanks for the clarification, I now opened a PR on the other github page, would be great if someone could review and merge it, thanks! https://github.com/hsf-training/training-center/pull/94

**Comment by ariostas** [comment] 2024-09-23 15:45
Could someone with the right permissions review and merge #1589? I merged https://github.com/hsf-training/training-center/pull/94, so we can close this issue after that.

**Comment by amorenobr** [comment] 2024-09-23 15:54
Done!

**Comment by graeme-a-stewart** [comment] 2024-09-25 10:33
Thanks for the fix @ariostas and for raising the issue @martamaja10

**Closed by graeme-a-stewart** 2024-09-25 10:33 UTC
